### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by SFort** [SFort/MC-SurvivalFlight#2]
- [x] "remove firework boosting" from curse by Slimation
- [x] apply the scripting system to elytras
- [x] add special script value which prevents it from being applied
